# @format

name: Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: install linter
        run: npm i
      - name: run prettier
        run: npx prettier . --w
      - name: cleanup + report
        run: echo "Finished linting!"
